import Navbar from "@/components/app/Navbar";
import { useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/navigation";

export default function Projects() {
  const { status } = useSession();
  const router = useRouter();

  if (status === "unauthenticated") {
    router.replace("/");
  }

  return status !== "authenticated" ? (
    <>Loading...</>
  ) : (
    <>
      <Head>
        <title>Projects</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
      </main>
    </>
  );
}

interface MainCardProps {
  title: string;
  path?: string;
  subtitle: string;
  onClick?: () => void;
  icon?: JSX.Element;
}

function MainCard(props: MainCardProps) {
  return (
    <Link href={props.path ?? "#"} onClick={props.onClick}>
      <div className="p-5 min-h-[130px] rounded-sm bg-white shadow-md outline outline-1 outline-gray-200">
        <div className="flex items-center gap-2">
          {props.icon}
          <h1 className="text-xl font-semibold">{props.title}</h1>
        </div>
        <p>{props.subtitle}</p>
      </div>
    </Link>
  );
}
